name: Rust

on:
  push:
    branches: [ main, structure_revamp ]
  pull_request:
    branches: [ main, structure_revamp ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: HDF5
      run: |
        sudo apt-get update
        sudo apt-get install libhdf5-serial-dev
    - name: Build
      working-directory: meteomatics
      run: cargo build
    - name: Run tests
      working-directory: meteomatics
      run: cargo test
